namespace LLE.ModelGateway.Enums
{
    /// <summary>
    /// Represents the origin/role of a message within a chat completion flow.
    /// </summary>
    public enum ChatMessageRole : byte
    {
        /// <summary>
        /// System-level instruction or context used to guide model behaviour.
        /// </summary>
        System,

        /// <summary>
        /// Message originating from the end user.
        /// </summary>
        User,

        /// <summary>
        /// Message generated by the assistant model.
        /// </summary>
        Assistant,

        /// <summary>
        /// Message produced by an external tool or function call result.
        /// </summary>
        Tool
    }
}